myblog/blog/urls.py
from django.urls import path
from . import views
from .views import AddCommit

urlpatterns = [
    path('', views.PostView.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('comment/<int:pk>/', AddCommit.as_view(), name='comment')
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
# from blog import views as poll_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField("Заголовок записи", max_length=100)
    description = models.TextField("Текскт записи")
    author = models.CharField("Имя автора", max_length=100)
    date = models.DateField("Дата")
    img = models.ImageField(" Фотка", upload_to='files')

    def __str__(self):
        return f'{self.title}, {self.author}'



    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"



class Commit(models.Model):
    email = models.EmailField()
    name = models.CharField("Имя", max_length=60)
    text = models.TextField("Текст", max_length=1500)
    post = models.ForeignKey(Post, verbose_name="Публикации", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'



    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post
from .form import CommitForm
# Create your views here.

class PostView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})



class PostDetail(View):
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/detail.html', {'post': post})


class AddCommit(View):
    def post(self, request, pk):
        form = CommitForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')

myblog/blog/templates/blog/blog.html
{% load static %}

<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>

			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects" style="height: 210px; margin-bottom: 50px">
					<h3>Записи</h3>
					<div class="item">
					{% for post in post_list %}
						<div class="image left">
							<a href="#"><img src="{{ post.img.url }}" width="250px" /></a>
						</div>
						<div class="text left" style="margin-left: 60px; font-size: 18px;line-height: 1.5;">
							<h2><a href="{{ post.id }}"> {{ post.title }} </a></h2><br>
							<p>{{ post.description }}</p><br>
							<p>Автор: {{ post.author }} </p><br>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
					{% endfor %}

				</div>
			</div>

			<div class="cl">&nbsp;</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>

myblog/blog/templates/blog/detail.html
{% load static %}

<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>

			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects" style="height: 210px; margin-bottom: 50px">
					<h3>{{ post.title }}</h3>
                    <p align="center">
                        <a href="#"><img src="{{ post.img.url }}" width="50%" /></a>
                    </p><br>
					<div class="item">
						<div class="text left" style="margin-left: 60px; font-size: 18px;line-height: 1.5;">
							<p>{{ post.description }}</p><br>
							<p>Автор: {{ post.author }} </p><br>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
				</div>
			</div>
			<div class="cl">&nbsp;</div>
		</div>
		<div class="form-commit">
			<h2 style="margin-left: 60px">Оставить комментрий</h2>
			<div>
				<form action="{% url 'comment' post.id %}" method="post">
					{% csrf_token %}
					<div>
						<label>Ваш комментарий</label>
						<textarea name="text"></textarea>
					</div>
					<div>
						<label>Ваше имя</label>
						<input type="text" name="name">
					</div>
					<div>
						<label>Ваш email</label>
						<input type="email" name="email">
					</div>
					<input type="submit">
				</form>
			</div>
		</div>
		<div>
			<h2>Комментарии</h2>
			{% for comment in post.commit_set.all %}
			<div class="ddq">
				<h4>Пользователь: {{ comment.name }} </h4>
				<p>
					{{ comment.text }}
				</p>
			</div>
			{% endfor %}
		</div>

	</div>




	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>